name: Random Multi Booster

on:
  workflow_dispatch:

jobs:
  booster:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install atproto

      - name: Run Random Multi Booster
        env:
          BSKY_USERNAME: ${{ secrets.BSKY_USERNAME_EYESCANDY }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD_EYESCANDY }}
        run: |
          python random_multi_booster.py